version: '3'

services:
  mysql:
    container_name: lupin_mysql
    image: mysql
    command:
      - --lower_case_table_names=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_bin
    environment:
      - MYSQL_USER=developer
      - MYSQL_PASSWORD=1234
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=lupin
      - TZ=UTC
    restart: always
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306

  redis:
    container_name: lupin_redis
    image: redis
    volumes:
      - cache:/data
    ports:
      - 6379:6379
    restart: unless-stopped

networks:
  default:

volumes:
  mysql:
  cache:
